name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: ./gradlew build
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
          body: |
            ## LumaTrivia ${{ env.VERSION }}
            
            ### Installation
            1. Download the JAR file
            2. Place it in your server's `plugins` folder
            3. Restart your server
            4. Configure the plugin in `plugins/LumaTrivia/config.yml`
            
            ### Configuration
            See the [configuration guide](https://github.com/BadgersMC/LumaTrivia/wiki/Configuration) for detailed settings.
            
            ### Compatibility
            - Requires Paper 1.20.4+
            - Java 17+
